name: Produce PDF

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  produce-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CV repository
        uses: actions/checkout@v4
      
      - name: Produce PDF
        run: make produce_pdf
      
      - name: Generate date
        id: date
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: cv-${{ steps.date.outputs.date }}
          name: CV ${{ steps.date.outputs.date }}
          files: pdf/niels-degrande-cv.pdf
